services:
  rtgids-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtgids-backend-gpu
    restart: always
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://rtgids-redis:6379/0
      - RTGIDS_MODELS_DIR=/data/models
      - RTGIDS_API_TOKEN=dev-token-abc
      - RTGIDS_JWT_SECRET=supersecret
    volumes:
      - ./backend:/app
      - ./RealTime_IDS/models:/data/models
    depends_on:
      - rtgids-redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  rtgids-redis:
    image: redis:7
    container_name: rtgids-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data/redis:/data
